---
- name: Install ZK REG packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "zk-mgmt-plugin"
    - "zkregcli"
    
- name: Install ZK Replication packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "mfdd-zkrepl-patterns"
