#!/usr/bin/with-contenv /bin/bash

source /opt/adp/bin/base-common.sh

tag="$APP_NAME"
if [ ! -z "$APP_NAME_ELASTICSEARCH" ]
then
  tag="$APP_NAME_ELASTICSEARCH"
fi

exec s6-setuidgid root $ADP_BIN/service-management-agent.sh --logstash-config $SERVICE_NAME_ELASTICSEARCH $tag ELASTICSEARCH_HOSTS $ADP_CONF/logstash.conf.template $FILE_LOGSTASH_CONF $SD_DISCOVER_INTERVAL_ELASTICSEARCH
